### ISSUE TITLE
Flexbox align-self property not working

### ISSUE THREAD

**Issue by manish0870** [manish0870/HTML-Cheatsheet#1]
[` .item-2 {
                order: 2;
                align-self: center;
}`](https://github.com/manish0870/HTML-Cheatsheet/blob/master/flex-align.html)

**Comment by sparkle-sparkle** [comment]
From what I can tell the text is centered. What do you mean exactly? What makes you say it's invalid? What do you expect it should be like?

**Comment by manish0870** [comment]
@sparkle-sparkle  Actually, align-self insures the verticle alignment of the item but that is not happening here. 
![align self ex](https://user-images.githubusercontent.com/45981209/66590834-44590680-ebaf-11e9-8e2c-5174a2bbdf30.PNG)
Like in this picture, Item 2 should be in the center of the black container, and not on the top.

**Comment by sparkle-sparkle** [comment]
Oh, it should be here:
![image](https://user-images.githubusercontent.com/745519/66632244-47ccac00-ec08-11e9-9394-aa9a96d0b953.png)

**Comment by sparkle-sparkle** [comment]
I would like to work on this :-)

**Comment by manish0870** [comment]
@sparkle-sparkle  Thanks man for the fix.
